<?php
return [
    'merchant_id' => env('CS_MERCHANT_ID', 'testrest'),
    'api_key_id' => env('CS_KEY_ID', '08c94330-f618-42a3-b09d-e1e43be5efda'),
    'secret_key' => env('CS_SECRET_KEY', 'SOMEFAKEKEY'),
    'enable_log' => env('CS_ENABLE_LOG', false),
    'auth_type' => env('CS_AUTH_TYPE', 'http_signature'),
    'run_env' => env('CS_RUN_ENV', 'apitest.cybersource.com'),
    'log_file_name' => env('CS_LOG_FILE_NAME', 'Cybs.log'),
    'log_file' => env('CS_LOG_FILE', 'logs'),
    'log_size' => env('CS_LOG_SIZE', '1048576'),
    'log_date_format' => env('CS_LOG_DATE_FORMAT', 'Y-m-d\TH:i:s'),
    'log_format' => env('CS_LOG_DATE_FORMAT', "[%datetime%] [%level_name%] [%channel%] : %message%\n"),
    'log_max_files' => env('CS_LOG_MAX_FILES', 3),
    'log_level' => env('CS_LOG_LEVEL', 'error'),
    'enable_masking' => env('CS_ENABLE_MASKING', true),
    'key_directory' => env('CS_KEY_DIRECTORY', 'Resources/'),
    'use_meta_key' => env('CS_USE_META_KEY', false),
    'portfolio_id' => env('CS_PORTFOLIO_ID', ''),
];
