<?php

namespace Jauntin\CyberSource\Tests\Unit\Api\Internal;

use Illuminate\Support\Facades\App;
use Jauntin\CyberSource\Api\Internal\MicroformSessionResponseAdapter;
use Jauntin\CyberSource\Api\MicroformSessionResponse;
use Jauntin\CyberSource\Tests\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;

class MicroformSessionResponseAdapterTest extends TestCase
{
    #[DataProvider('fromResponseDataProvider')]
    public function test_from_response(string $response)
    {
        $result = App::make(MicroformSessionResponseAdapter::class)->fromResponse($response);
        $this->assertInstanceOf(MicroformSessionResponse::class, $result);
        $this->assertMatchesSnapshot($result);
    }

    public static function fromResponseDataProvider()
    {
        return [
            'successfulResponse' => ['eyJraWQiOiJ6dSIsImFsZyI6IlJTMjU2In0.eyJmbHgiOnsicGF0aCI6Ii9mbGV4L3YyL3Rva2VucyIsImRhdGEiOiJnOVVnaDNpelpGMUFaTTFvRGhmR0RCQUFFUGR1WFB2L3lZODlNTUxOMG9BMlpoM0JjekR4SVVvcERHVmtKM1Q1RGd0L1lZVVFCNUk0bjJ4NkNVNmtTSUVTMFEwaXk4Vm5DUS96QWRMbEx2empDbFAyWUhSY293WThuSGJlcmordHBHR2ciLCJvcmlnaW4iOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbSIsImp3ayI6eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsInVzZSI6ImVuYyIsIm4iOiJsS0poeUsxOE5BS2p0RXdVUXJZUnVVNGVrX3VDcUotLVVGcFRRWTc2VjNaYTVZcGt6UjBNUEZhWTF6OERodmREbDI4MUtlNXZyS1Ezb3pFWDF3eXdZaDM5LVFicldfaHhoSTlNdlRLSmU5MmxWLWhOQlJzYVExSUgtc0J5M2Y4Z0JCN1NYSDNnVndxWC0tTUlESi1PYmJiY0RtQ1hucHpubUVnY2tfbWpLQVM4V3ZadWJCamYwdVNzN2czbDhTalJoX1hodFFWcDAyUWhUUlYzajVQU2ltb1pOUzJxUlo0c2V4aDBoN3ZnSzlQdGRaaXhsaXBlX3FMV0tDcFZuQUNFcEFqb01UVTJtT05UeXpOajMyeFRRV2xJcWxoZVQ1LW9qTV9MYmhIZE9wSHphcFNfZEE5ZTV2NGZoMlp0Ul9Cc1RPNWhjSkxxMDJFdVR1WEprTUFocnciLCJraWQiOiIwN3FMZmk0cHgzUWtjZURmMExxdHZBZzVJT1hjeUs4WCJ9fSwiY3R4IjpbeyJkYXRhIjp7ImNsaWVudExpYnJhcnlJbnRlZ3JpdHkiOiJzaGEyNTYtNGtxcmNKTExuRGJLTStOYW9uYXhVZzhSV3A4Tm10bmpRbzdQSmNXckx6Z1x1MDAzZCIsImNsaWVudExpYnJhcnkiOiJodHRwczovL3Rlc3RmbGV4LmN5YmVyc291cmNlLmNvbS9taWNyb2Zvcm0vYnVuZGxlL3YyLjYuMC9mbGV4LW1pY3JvZm9ybS5taW4uanMiLCJhbGxvd2VkQ2FyZE5ldHdvcmtzIjpbIlZJU0EiLCJNQVNURVJDQVJEIiwiQU1FWCIsIkNBUk5FVCIsIkNBUlRFU0JBTkNBSVJFUyIsIkNVUCIsIkRJTkVSU0NMVUIiLCJESVNDT1ZFUiIsIkVGVFBPUyIsIkVMTyIsIkpDQiIsIkpDUkVXIiwiTUFEQSIsIk1BRVNUUk8iLCJNRUVaQSJdLCJ0YXJnZXRPcmlnaW5zIjpbImh0dHBzOi8vd3d3LnRlc3QuY29tIl0sIm1mT3JpZ2luIjoiaHR0cHM6Ly90ZXN0ZmxleC5jeWJlcnNvdXJjZS5jb20iLCJhbGxvd2VkUGF5bWVudFR5cGVzIjpbIkNBUkQiXX0sInR5cGUiOiJtZi0yLjEuMCJ9XSwiaXNzIjoiRmxleCBBUEkiLCJleHAiOjE3NTAyNjg5NzIsImlhdCI6MTc1MDI2ODA3MiwianRpIjoiejk2amhWWnkwMms5SFRJWSJ9.UXf8zOjXY4qg1Pe0eL03pVEN01tYsOrEWrG8GZEdFp6qPt5erh_0a3OuXwzmNJ90VQvo7M0VZBJxid5KGc_yrcCHrkG33_kb5ZXkJjev2X80WBk_RGj8ymnXN00dF9_iU87jonJtXm8Vo7H9fU8gGL6kOAnql81OSsFFG73Iqgu0n6jpQG8u5145MYodriOvTZndC0UdQJIXCA554OdCioFvkgwFENqNb6pKtVunfg-401EUv9_BIEi0OdA2IjG41uz2Xw6u59CBWZsDPkUEotAPG34Nj5mmjCcTW2AXtNR3UZAwXF4NoB6sZXr0GD3g50qCfqKOwJ4Rr5OpfhyREw'],
        ];
    }
}
